// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as RelayEnv from "./RelayEnv.res.mjs";
import * as RescriptRelay from "rescript-relay/src/RescriptRelay.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactDOMExperimental from "rescript-relay/src/ReactDOMExperimental.res.mjs";

import './index.css'
;

ReactDOMExperimental.renderConcurrentRootAtElementWithId(JsxRuntime.jsx(RescriptRelay.Context.Provider.make, {
          environment: RelayEnv.environment,
          children: JsxRuntime.jsx(App.make, {})
        }), "root");

export {
  
}
/*  Not a pure module */
